import java.util.ArrayList;
import java.util.Random;

public abstract class Computer {
    String secretCode;

    public Computer() {
        // generate secret code when the computer object is created
        secretCode = generateSecretCode();
    }

    // generate a secret code by selecting 4 random digits from 0 to 9
    protected String generateSecretCode() {
        // create ArrayList of available digits
        ArrayList<Integer> digits = new ArrayList<>();
        for (int i = 0; i <= 9; i++) {
            digits.add(i);
        }

        // choose 4 random digits from list of available digits and append to a StringBuilder
        StringBuilder code = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < 4; i++) {
            int index = random.nextInt(digits.size());
            code.append(digits.get(index));
            digits.remove(index);
        }

        // return generated code as String
        return code.toString();
    }

    // return the code generated by the computer
    public String getSecretCode() {
        return secretCode;
    }

    // method is abstract, must be implemented by any class that inherits from Computer
    public abstract String makeGuess();
}
